# Generated by Django 4.1 on 2022-10-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_blog_img_alter_blog_subtitulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
