# Generated by Django 4.1 on 2022-10-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_delete_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
