# Generated by Django 4.1 on 2022-10-11 00:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_blog_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cuerpo',
            field=tinymce.models.HTMLField(),
        ),
    ]
