# Generated by Django 4.1 on 2022-10-11 11:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', tinymce.models.HTMLField()),
                ('autor', models.CharField(max_length=100)),
                ('receptor', models.CharField(max_length=100)),
            ],
        ),
    ]
